In [1]:
import numpy as np
import pandas as pd

In [4]:
df_cov = pd.read_csv("../../compile-data/out/covar.tsv", sep='\t', index_col=0)

In [6]:
df_cov[df_cov['group'] != "United Kingdom"]

,AGE,SEX,DEPRIVATION_INDEX,PC1,PC2,PC3,PC4,PC5,PC6,PC7,...,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,group,GENET_DIST
INDIV,,,,,,,,,,,,,,,,,,,,,
5501069,60,0,-0.982022,-12.43740,2.76059,-0.248736,4.088450,1.19011,0.457771,0.655166,...,5.861100,3.397410,5.096530,-2.286110,-0.793386,-1.355980,2.375940,2.969970,NaN,NaN
3008039,43,1,-1.102330,-14.36620,2.62983,-3.526230,2.780420,-1.39331,1.024670,-2.420870,...,1.900460,0.071396,4.492930,-3.185060,-0.780388,1.524980,-0.538120,-1.654040,NaN,NaN
4799507,43,1,1.489100,-7.88334,-2.96238,-0.827765,3.934140,-6.78809,25.312200,-38.342900,...,-3.999830,-6.539900,11.164600,1.750870,0.886005,0.954219,2.344890,-3.548290,Poland,0.035946
1779792,57,0,-2.644990,-11.53820,2.35427,-0.592917,3.780340,-1.12586,1.548000,1.147920,...,3.665320,2.739120,0.555437,-0.765744,-0.297290,1.242590,1.029230,0.565300,NaN,NaN
2678693,60,0,-1.307780,-13.69880,1.73149,-2.755210,-0.420287,-3.06482,0.245661,-3.090410,...,-1.151000,-0.535815,4.225150,-5.013810,2.656780,-1.730370,2.525890,-0.593719,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470366,60,1,0.905939,200.36700,-81.58280,-16.867000,4.133570,-1.42920,-5.605770,-1.444900,...,-0.307163,-12.625700,5.027030,-1.575110,15.546400,-4.558830,-18.986400,6.406300,NaN,NaN
3135174,46,0,1.255520,-13.97340,3.41305,-1.719330,6.692040,8.66174,3.543460,-1.286770,...,2.688960,-1.060450,0.206323,-3.235770,1.103070,-1.094670,2.519140,-0.267587,NaN,NaN
3928276,51,0,0.222304,-11.74780,3.17302,-1.217540,-2.091000,-6.47155,-1.041700,1.998860,...,1.074250,-0.058005,-2.240320,3.256960,-2.065560,-7.884780,-1.621500,-3.029820,NaN,NaN
4031831,51,0,-1.612000,-14.07350,2.46635,-1.064270,0.890216,-1.34540,-0.220376,-0.910067,...,-5.810210,0.703184,1.439180,0.403231,-1.738990,1.511090,-1.169610,1.838940,NaN,NaN
5738092,45,0,-4.105290,64.82530,-118.29300,-44.576000,-1.784150,2.40612,-10.122300,0.850589,...,1.629030,-0.606739,-0.046524,-4.451810,28.438500,-2.982960,-0.494746,-0.549634,NaN,NaN